#pragma once
// One include for everything:  #include "simplegui/simplegui.h"

#include "simplegui/application.h"
#include "simplegui/window.h"
#include "simplegui/control.h"
#include "simplegui/event_connection.h"
#include "simplegui/timer.h"
#include "simplegui/dialogs.h"

// Layouts
#include "simplegui/vbox.h"
#include "simplegui/hbox.h"
#include "simplegui/grid.h"
#include "simplegui/group_box.h"
#include "simplegui/tab_view.h"
#include "simplegui/split_view.h"
#include "simplegui/scroll_view.h"

// Basic Input & Display
#include "simplegui/button.h"
#include "simplegui/label.h"
#include "simplegui/text_input.h"
#include "simplegui/password_input.h"
#include "simplegui/search_field.h"
#include "simplegui/textarea.h"
#include "simplegui/list_box.h"
#include "simplegui/checkbox.h"
#include "simplegui/radio.h"
#include "simplegui/dropdown.h"
#include "simplegui/combo_box.h"
#include "simplegui/slider.h"
#include "simplegui/knob.h"
#include "simplegui/number_input.h"
#include "simplegui/progress_indicator.h"
#include "simplegui/circular_progress.h"
#include "simplegui/date_picker.h"
#include "simplegui/color_well.h"
#include "simplegui/rating.h"
#include "simplegui/breadcrumbs.h"
#include "simplegui/link.h"
#include "simplegui/image.h"
#include "simplegui/image_button.h"
#include "simplegui/web_view.h"

// Modern Telemetry & Analytics Controls
#include "simplegui/sparkline.h"
#include "simplegui/vfd_meter.h"
#include "simplegui/stat_card.h"
#include "simplegui/composition_bar.h"
#include "simplegui/status_pill.h"

// High-Level Composite & Parity Controls
#include "simplegui/activity_heatmap.h"
#include "simplegui/stat_grid.h"
#include "simplegui/user_profile_card.h"
#include "simplegui/product_card.h"
#include "simplegui/donut_chart.h"
#include "simplegui/kanban_board.h"
#include "simplegui/feedback_mood.h"
#include "simplegui/date_range_picker.h"
#include "simplegui/masked_input.h"
#include "simplegui/token_field.h"
#include "simplegui/nav_rail.h"
#include "simplegui/media_player.h"

// Graphics & Advanced Charts
#include "simplegui/bar_chart.h"
#include "simplegui/line_chart.h"
#include "simplegui/pie_chart.h"
#include "simplegui/canvas.h"
#include "simplegui/radar_chart.h"
#include "simplegui/candlestick_chart.h"

// Futuristic controls
#include "simplegui/toggle_switch.h"
#include "simplegui/radial_gauge.h"
#include "simplegui/neon_button.h"
#include "simplegui/led_indicator.h"
#include "simplegui/radar_scope.h"
#include "simplegui/terminal_view.h"
#include "simplegui/segmented_control.h"
#include "simplegui/glass_panel.h"

// New Controls (v0.2)
#include "simplegui/tree_view.h"
#include "simplegui/accordion.h"
#include "simplegui/toast.h"
#include "simplegui/time_picker.h"
#include "simplegui/calendar_view.h"
#include "simplegui/rich_text_editor.h"
#include "simplegui/menu_bar.h"
#include "simplegui/toolbar.h"
#include "simplegui/form_layout.h"
#include "simplegui/flow_layout.h"
#include "simplegui/property_grid.h"
#include "simplegui/path_picker.h"
#include "simplegui/signature_pad.h"
#include "simplegui/timeline.h"
#include "simplegui/markdown_viewer.h"
#include "simplegui/carousel.h"
#include "simplegui/code_editor.h"
#include "simplegui/data_form.h"
#include "simplegui/gantt_chart.h"
#include "simplegui/gauge_cluster.h"
#include "simplegui/heatmap_calendar.h"

// Familiar names (Edit, Memo, CheckBox, TrackBar, ...)
#include "simplegui/aliases.h"
